### ISSUE TITLE
Failing at NPM build

### ISSUE THREAD

**Issue by Lockwos** [IBM/cognitive-social-crm#57]
I am NOT and expert with npm etc but tried to follow the instructions in the readme.
Felt there were several issues:
1) Video seemed well out of date and had a app/tool shown in it that doesn't exist in latest build?
2) Distinction between local and cloud builds weren't really clear
3) Explanation of manifest.yml entries and .env entires would be useful as those are key
4) when tried to use npm run build got this output
######################################################################
[1]
[1] > cognitive-social-crm@1.0.0 preinstall:server C:\Users\SteveLockers\cognitive-social-crm
[1] > cd server && rm -rf dist
[1]
[0]
[0] > cognitive-social-crm@1.0.0 preinstall:client C:\Users\SteveLockers\cognitive-social-crm
[0] > cd client && rm -rf dist
[0]
[1] npm run preinstall:server exited with code 0
[0] npm run preinstall:client exited with code 0
[1]
[1] > cognitive-social-crm@1.0.0 build:server C:\Users\SteveLockers\cognitive-social-crm
[1] > cd server && npm run build
[1]
[0]
[0] > cognitive-social-crm@1.0.0 build:client C:\Users\SteveLockers\cognitive-social-crm
[0] > cd client && npm run build
[0]
[1]
[1] > server@1.0.0 build C:\Users\SteveLockers\cognitive-social-crm\server
[1] > node ./node_modules/.bin/tsc && cp package.json dist
[1]
[0]
[0] > cognitive-social-crm@0.0.1 build C:\Users\SteveLockers\cognitive-social-crm\client
[0] > ./node_modules/@angular/cli/bin/ng build
[0]
[0] '.' is not recognized as an internal or external command,
[0] operable program or batch file.
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! cognitive-social-crm@0.0.1 build: `./node_modules/@angular/cli/bin/ng build`
[0] npm ERR! Exit status 1
npm ERR!
[0] npm ERR! Failed at the cognitive-social-crm@0.0.1 build script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     C:\Users\SteveLockers\AppData\Roaming\npm-cache\_logs\2018-10-01T15_01_24_180Z-debug.log
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! cognitive-social-crm@1.0.0 build:client: `cd client && npm run build`
[0] npm ERR! Exit status 1
npm ERR!
[0] npm ERR! Failed at the cognitive-social-crm@1.0.0 build:client script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     C:\Users\SteveLockers\AppData\Roaming\npm-cache\_logs\2018-10-01T15_01_24_226Z-debug.log
[0] npm run build:client exited with code 1
[1] C:\Users\SteveLockers\cognitive-social-crm\server\node_modules\.bin\tsc:2
[1] basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
[1]           ^^^^^^^
[1]
[1] SyntaxError: missing ) after argument list
[1]     at createScript (vm.js:80:10)
[1]     at Object.runInThisContext (vm.js:139:10)
[1]     at Module._compile (module.js:617:28)
[1]     at Object.Module._extensions..js (module.js:664:10)
[1]     at Module.load (module.js:566:32)
[1]     at tryModuleLoad (module.js:506:12)
[1]     at Function.Module._load (module.js:498:3)
[1]     at Function.Module.runMain (module.js:694:10)
[1]     at startup (bootstrap_node.js:204:16)
[1]     at bootstrap_node.js:625:3
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! server@1.0.0 build: `node ./node_modules/.bin/tsc && cp package.json dist`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the server@1.0.0 build script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\SteveLockers\AppData\Roaming\npm-cache\_logs\2018-10-01T15_01_24_574Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! cognitive-social-crm@1.0.0 build:server: `cd server && npm run build`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the cognitive-social-crm@1.0.0 build:server script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\SteveLockers\AppData\Roaming\npm-cache\_logs\2018-10-01T15_01_24_619Z-debug.log
[1] npm run build:server exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognitive-social-crm@1.0.0 build: `concurrently "npm run preinstall:client" "npm run preinstall:server" && concurrently "npm run build:client" "npm run build:server"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognitive-social-crm@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SteveLockers\AppData\Roaming\npm-cache\_logs\2018-10-01T15_01_24_695Z-debug.log
#############################################################################

I'd love to get the demo going as it looks like a great app to show customers and has multiple services all working in harmony alongside external service that is Twitter

**Comment by sanjeevghimire** [comment]
@Lockwos  I tested it locally and also tested deploying to IBM cloud and it works fine for me. This is the app I was able to deploy: `crm-client.mybluemix.net`

p.s. I did find a minor mistake when deploying to IBM cloud when building. I have fixed that. But your issue seems to be during installation of dependencies.

**Comment by bryan-ninjamoba** [comment]
Sanjeev - we are glad you got this running but I am also stuck at the following exact concerns: also what was your minor mistake????!?!?


> * Video seemed well out of date and had a app/tool shown in it that doesn't exist in latest build?
> * Distinction between local and cloud builds weren't really clear
> * Explanation of manifest.yml entries and .env entires would be useful as those are key
> * when tried to use npm run build got this output

Can we get an update on these issues please - these are unrelated to installation of dependencies.

These issues remain unresolved.

**Comment by bryan-ninjamoba** [comment]
Windows 10

**Comment by sanjeevghimire** [comment]
@bryan-ninjamoba currently the npm scripts don't support windows as it is running `rm` commands part of it. I will try to see if there is an alternate way so that its platform agnostic.

**Comment by stevemart** [comment]
Windows OS is not supported and not on our roadmap of things to address in this repo.

We also revamped the instructions to address some of the initial concerns in commit https://github.com/IBM/cognitive-social-crm/commit/511eaf6eaec7f78e2a78e727412b8d70824ccce7
